import turtle

angle = 90
forward_length = 1

print("Python is executed")

class Outputter:
	def __init__(self):
		self.window = turtle.Screen()
		self.window.title("Turtle Graphics Module: Generated by NextGen")
		self.window.bgcolor('black');
		self.babbel057 = turtle.Turtle()
		self.babbel057.penup()
		#self.babbel057.goto(-500,300)
		self.babbel057.shape('turtle')
		self.babbel057.speed(0)
		self.babbel057.pensize(2)
		self.babbel057.color('cyan')
		self.babbel057.pendown()

	def output(self, s):
		if s == '+':
			self.babbel057.right(angle)
		if s == '-':
			self.babbel057.left(angle)
		else:
			self.babbel057.forward(forward_length)
        
	def close(self):
		self.window.mainloop()

#f = lambda r: r.replace("F", "F+F-F-F+F")

#o = Outputter()
#for symb in f(f(f(f(f("F"))))):
#	o.output(symb)

#o.close()

