import turtle

angle = 15
forward_length = 1

print("Python is executed")

class Outputter:
	def __init__(self):
		self.window = turtle.Screen()
		self.window.title("Turtle Graphics Module: Generated by NextGen")
		self.window.bgcolor('black');
		babbel057 = turtle.Turtle()
		babbel057.shape('turtle')
		babbel057.speed(5)
		babbel057.pensize(2)
		babbel057.color('cyan')
		babbel057.pendown()

    def output(self, s):
        if s == '+':
        	babbel057.right(angle)
		if s == '-':
			babbel057.left(angle)
		else:
			babbel057.forward(forward_length)
        
    def close(self):
    	self.window.mainloop()
