
# warning, HACK

.PHONY build:
build:
	#./b2 install --prefix=b2stuff cxxflags="-I\"../python3/Include/\" -I\"../python3/\""
	# Change python3.4m if python is installed somewhere else
	# Baker detects this, but I'm too lazy to pass through that info
	./b2 install --prefix=b2stuff cxxflags="-I\"/usr/include/python3.4m/\""


