# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target

# Include any dependencies generated for this target.
include test/cpp/gtester/CMakeFiles/gtester.dir/depend.make

# Include the progress variables for this target.
include test/cpp/gtester/CMakeFiles/gtester.dir/progress.make

# Include the compile flags for this target's objects.
include test/cpp/gtester/CMakeFiles/gtester.dir/flags.make

test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/main.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/main.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/main.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/main.cpp > CMakeFiles/gtester.dir/main.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/main.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/main.cpp -o CMakeFiles/gtester.dir/main.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o


test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCircular.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/UnitCircular.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCircular.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/UnitCircular.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCircular.cpp > CMakeFiles/gtester.dir/UnitCircular.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/UnitCircular.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCircular.cpp -o CMakeFiles/gtester.dir/UnitCircular.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o


test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCumulativeRecords.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCumulativeRecords.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCumulativeRecords.cpp > CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitCumulativeRecords.cpp -o CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o


test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitConstCircular.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/UnitConstCircular.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitConstCircular.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/UnitConstCircular.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitConstCircular.cpp > CMakeFiles/gtester.dir/UnitConstCircular.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/UnitConstCircular.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitConstCircular.cpp -o CMakeFiles/gtester.dir/UnitConstCircular.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o


test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitQuad.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/UnitQuad.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitQuad.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/UnitQuad.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitQuad.cpp > CMakeFiles/gtester.dir/UnitQuad.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/UnitQuad.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitQuad.cpp -o CMakeFiles/gtester.dir/UnitQuad.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o


test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitRecords.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/UnitRecords.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitRecords.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/UnitRecords.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitRecords.cpp > CMakeFiles/gtester.dir/UnitRecords.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/UnitRecords.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitRecords.cpp -o CMakeFiles/gtester.dir/UnitRecords.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o


test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o: test/cpp/gtester/CMakeFiles/gtester.dir/flags.make
test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o: /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitSegmentedVector.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o -c /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitSegmentedVector.cpp

test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.i"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitSegmentedVector.cpp > CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.i

test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.s"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && /usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester/UnitSegmentedVector.cpp -o CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.s

test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.requires:

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.requires

test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.provides: test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.requires
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.provides.build
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.provides

test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.provides.build: test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o


# Object files for target gtester
gtester_OBJECTS = \
"CMakeFiles/gtester.dir/main.cpp.o" \
"CMakeFiles/gtester.dir/UnitCircular.cpp.o" \
"CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o" \
"CMakeFiles/gtester.dir/UnitConstCircular.cpp.o" \
"CMakeFiles/gtester.dir/UnitQuad.cpp.o" \
"CMakeFiles/gtester.dir/UnitRecords.cpp.o" \
"CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o"

# External object files for target gtester
gtester_EXTERNAL_OBJECTS =

test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/build.make
test/cpp/gtester/gtester: test/resources/lib/gtest/libgtest.a
test/cpp/gtester/gtester: test/cpp/gtester/CMakeFiles/gtester.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Linking CXX executable gtester"
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/gtester.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
test/cpp/gtester/CMakeFiles/gtester.dir/build: test/cpp/gtester/gtester

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/build

test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/main.cpp.o.requires
test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCircular.cpp.o.requires
test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/UnitCumulativeRecords.cpp.o.requires
test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/UnitConstCircular.cpp.o.requires
test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/UnitQuad.cpp.o.requires
test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/UnitRecords.cpp.o.requires
test/cpp/gtester/CMakeFiles/gtester.dir/requires: test/cpp/gtester/CMakeFiles/gtester.dir/UnitSegmentedVector.cpp.o.requires

.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/requires

test/cpp/gtester/CMakeFiles/gtester.dir/clean:
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester && $(CMAKE_COMMAND) -P CMakeFiles/gtester.dir/cmake_clean.cmake
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/clean

test/cpp/gtester/CMakeFiles/gtester.dir/depend:
	cd /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/cpp/gtester /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester /Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/target/test/cpp/gtester/CMakeFiles/gtester.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : test/cpp/gtester/CMakeFiles/gtester.dir/depend

