# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -std=c++11 -O3 -DNDEBUG -I/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/main/cpp -I/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/main/resources/lib/tclap/include -I/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/main/resources/lib/g2log/src -I/Bestanden/Copy/root/Bestanden/School/ADV_PROG/tracer/gobelijn/src/test/resources/lib/gtest   

CXX_DEFINES = -DGTEST_LANG_CXX11

